spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate auto-creates or updates tables based on your Java entities
spring.jpa.hibernate.ddl-auto=update
# Console mein SQL queries dekhne ke liye (debugging mein help karega)
spring.jpa.show-sql=true